### ISSUE TITLE
Add networking

### ISSUE THREAD

**Issue by pconrad** [UCSB-CS56-Projects/cs56-games-poker#1]
Allow this poker game to be playable over a socket connection.

Can maybe add a chat to allow players to communicate with one another.

See the client-server games and client-server chat for an some example code.

~points 400

**Comment by arda-** [comment]
after talking with sashasams and drewluo926, increasing value to 500 pts.

**Comment by arda-** [comment]
Splitting chat client into a new issue - see issue #21
