### ISSUE TITLE
improve README

### ISSUE THREAD

**Issue by arda-** [UCSB-CS56-Projects/cs56-games-poker#11]
The readme is good, but could be more welcoming and informative. It should have the following:

run instructions
(at least) a high level description of how the program works
an explanation of non-obvious ant targets like "images" or "linenumbers"
a description of the various files/directories
project history
screenshots

100 points.

**Comment by jalexanderqed** [comment]
The README has been significantly improved, but some of the links are broken, and it would be nice to have a description of program control flow and what the main files do.

**Comment by jalexanderqed** [comment]
F16 OK (60 pts)

**Comment by jalexanderqed** [comment]
The README was significantly improved in M16, including instructions for the next generation of students. Please continue this improvement and add your own instructions for the next set of students once you made your contributions.

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)
