### ISSUE TITLE
Several GUI Issues below

### ISSUE THREAD

**Issue by sashashams** [UCSB-CS56-Projects/cs56-games-poker#12]
Click to play window doesn't go away.
For classic holdem the flop should not be shown before a betting round. 
You can bet more than once. 
When you win, dealer doesn't show fold.
BETTING IN GENERAL DOESN'T WORK, it is not turn based.

**Comment by drewluo926** [comment]
Fix these bugs and refactoring the code in preparation for creating a multiplayer socket connection option should go for:  ~100 points

**Comment by arda-** [comment]
approved

**Comment by arda-** [comment]
fixed!
