### ISSUE TITLE
Make the game turn based

### ISSUE THREAD

**Issue by drewluo926** [UCSB-CS56-Projects/cs56-games-poker#14]
- Force blinds to be posted by both players prior to cards being dealt
- Allow betting/folding before flop is dealt, before turn is dealt, and before river is dealt
- Make the game turn based : in single player, the user will always bet first. in multiplayer, the dealer should alternate and the player not the dealer should always bet first.
- Game should progress without prompting for the turn or the river
- Messages should appear displaying action of the opposing player, and prompting for actions from the user

Points: ~300 or more?

**Comment by drewluo926** [comment]
This also required making significant changes to the GUI including rearranging all the buttons and panels. To be specific:
- Improve GUI significantly : ~100 points
- Make the game turn based (changing a lot of the way the game is inherently designed) : ~200 points

**Comment by arda-** [comment]
approved

**Comment by arda-** [comment]
feature implemented
