### ISSUE TITLE
Single Player Mode and Dealer AI

### ISSUE THREAD

**Issue by drewluo926** [UCSB-CS56-Projects/cs56-games-poker#16]
Refactor code in preparation for multiplayer socket connection, so that when run:
- Game offers a single player option as well as (yet to be implemented) multiplayer
- Have single player extend PokerGame and have the player play against computer
- Implement basic AI for dealer (computer)

Points: ~100

**Comment by arda-** [comment]
approved

**Comment by arda-** [comment]
feature implemented
