### ISSUE TITLE
Refactor code to follow a Model, View, Controller design pattern

### ISSUE THREAD

**Issue by drewluo926** [UCSB-CS56-Projects/cs56-games-poker#18]
(~400 points) Refactor the code to follow a model, view, controller design pattern, which means factor out the game mechanic logic from the GUI and user input. This would make it easier to change the GUI and game mechanics without breaking the game while doing so, and would allow for future improvements such as allowing beyond two players to a game. (see W16_lab10 for details)

**Comment by arda-** [comment]
W16 OK

**Comment by jalexanderqed** [comment]
F16 OK (300 pts)

**Comment by jalexanderqed** [comment]
F16 CLOSED: This has been superseded by #33
