### ISSUE TITLE
Bugfixes/Improvements on current multiplayer game

### ISSUE THREAD

**Issue by drewluo926** [UCSB-CS56-Projects/cs56-games-poker#19]
(~200 points) 
* The multiplayer clients and server do not disconnect and close upon exit of the game. Make it so they will exit gracefully, and/or take the user back to the main menu.
* The multiplayer version of the game does not handle the case where a player reaches 0 chips. (Check the single player version of the game for how this should be handled.)
* The chat client does not keep track of player IDs. Possibly allow the player create a nickname to be displayed when they talk in chat.

**Comment by arda-** [comment]
W16 OK

**Comment by jalexanderqed** [comment]
Also handle bad-input cases. For example when the user inputs an invalid IP address to connect to, the main window exits, but the process keeps running. All such cases should be handled gracefully.

**Comment by jalexanderqed** [comment]
F16 OK (200 pts)

**Comment by jalexanderqed** [comment]
F16 CLOSED: The multiplayer element was removed in M16
