### ISSUE TITLE
Improve Hand comparison to follow "best of five" format

### ISSUE THREAD

**Issue by drewluo926** [UCSB-CS56-Projects/cs56-games-poker#20]
(~300 points ??\* ) Current hand comparison in Hand.java does not determine the winner via "best of five", which results in some corner case hands winning when they should not. In the best of five format, which is traditional texas hold'em, only the best 5 cards should play. In the current implementation the best 7 cards play when comparing hands. (see W16_lab10 for details)

*unsure on point value for this one

**Comment by arda-** [comment]
W16 OK

**Comment by jalexanderqed** [comment]
I also encountered an issue where a tie was announced when one player had a pair of sevens and the other player had a pair of tens. In this case, the player with a pair of tens should win. Go over the hand comparison logic and check its correctness, including adding a unit test (#40).

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)

**Comment by jalexanderqed** [comment]
Hand comparison was restructure and moved to CompareHands.java in M16. However, this format is still correct and should be implemented.

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)
