### ISSUE TITLE
Unreadable Hand.java

### ISSUE THREAD

**Issue by dvanmali** [UCSB-CS56-Projects/cs56-games-poker#29]
Code is unreadable and does not utilize polymorphic and preexisting methods to the best of it's ability. Fix Hand.java to fix most of the corner cases when determining the winner. In order to better understand what is actually occurring in the code use correct syntax the class's syntax, use pre-existing functions, and inherited objects. For example, the sameHand() method is over a hundred lines of code, but what it does could be utilized by calling other methods again.

Estimate: ~150/200 pts

**Comment by jalexanderqed** [comment]
F16 CLOSED: This issue was resolved in M16
