### ISSUE TITLE
Integrate chat into multiplayer Issue #23 (Updated)

### ISSUE THREAD

**Issue by dvanmali** [UCSB-CS56-Projects/cs56-games-poker#31]
Right now chat needs to be set up separately from the multiplayer server of the game. Make chat automatically set up and display when connecting to a multiplayer server. 

(Originally) ~400 pts

**Part 1:** Setting up the button only within the Multiplayer Game (not Single Player): ~100 pts
Issues:
- Create a button to open the chat window

**Part 2:** Being able to chat with the other player: ~300 (additional) pts
Issues:
- Correctly reference the address passed in when starting the PokerServer
- Communication between two computers work

**Comment by jalexanderqed** [comment]
F16 CLOSED: This issue was made somewhat redundant by the M16 removal of the multiplayer poker server. Chat now works, but as a separate service.
