### ISSUE TITLE
Improve/Fix JavaDoc

### ISSUE THREAD

**Issue by dvanmali** [UCSB-CS56-Projects/cs56-games-poker#35]
Ant javadoc works but there are tons of errors and warnings upon compiling. Add parameter and class definitions before each function so there are no more errors and warnings when running 'ant javadoc.'

Estimate: ~50 pts

**Comment by mcaccamo** [comment]
m16 okay

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)
