### ISSUE TITLE
GUI Class

### ISSUE THREAD

**Issue by dvanmali** [UCSB-CS56-Projects/cs56-games-poker#36]
Create a new file to handle all of the Poker Game GUI stuff located at the bottom of PokerGame.java file.

Estimate: ~50 pts

**Comment by mcaccamo** [comment]
m16 okay

**Comment by jalexanderqed** [comment]
Make sure to move all of the data structures associated with the GUI (JFrame, JPanels, etc.) into this new GUI class.

**Comment by jalexanderqed** [comment]
F16 OK (70 pts)
