### ISSUE TITLE
Rules Sheet within Game

### ISSUE THREAD

**Issue by dvanmali** [UCSB-CS56-Projects/cs56-games-poker#37]
Make the Rules sheet a side panel within the Poker Game instead of creating a new window.

Estimate: ~50 pts

**Comment by mcaccamo** [comment]
m16 okay

**Comment by jalexanderqed** [comment]
Note that this side panel should not always be present, but should slide in and out when the button is pressed.

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)
