### ISSUE TITLE
Create a TestCompareHands.java

### ISSUE THREAD

**Issue by dvanmali** [UCSB-CS56-Projects/cs56-games-poker#40]
Create a file to test all combinations of hands and table cards to see if comparing actually works.

Estimate: ~150 pts

**Comment by mcaccamo** [comment]
m16 okay

**Comment by jalexanderqed** [comment]
F16 OK (150 pts)

**Comment by jalexanderqed** [comment]
The new test file looks good but does not seem to be run by `ant test` because it does not follow the naming convention *Test.java

**Comment by jalexanderqed** [comment]
I'm not sure why, but the test file still does not appear to run. To test it, try putting something in the test file that should DEFINITELY fail and run `ant test`. As far as I can tell, it's still not invoked at all.
