### ISSUE TITLE
Make AI separated from the PokerSinglePlayer class

### ISSUE THREAD

**Issue by gwhiter** [UCSB-CS56-Projects/cs56-games-poker#51]
Currently the AI is inside the PokerSinglePlayer (the only playable game mode) class. Most of the code is tightly linked, and this would be a step in the right direction for making the code more available to change. Separating it would aid in creating a multiplayer game, as single and multi player could be combined into one class, with a list of current players (AI or human), instead of the current inflexible single player class.

Est~250

**Comment by jalexanderqed** [comment]
F16 OK (250 pts)
