### ISSUE TITLE
Improve how CompareHands handles ties

### ISSUE THREAD

**Issue by The3TC** [UCSB-CS56-Projects/cs56-games-poker#56]
CompareHands has issues, mainly with how it deals with breaking up ties.  Add more tests to CompareHandsTest to check. There are two ways we considered fixing the issue.

One: Create a giant look up table. There is a lot of information online on how to do this. They are generally considered the fastest way to calculate the values of hands, and would probably be the best solution.

Two: Instead of having Calculate value return only one integer, have it return an array of integers. The first integer in the array represents the type of hand it is (ie Straight Flush has value 8, Highest Card has value 0). The second integer represents the rank within each type of hand (ie a Royal Flush would have a value of 14, a Straight Flush made up of A12345 would have a value of 5). To deal with ties, you’d refer to the second integer in the array. 
Both of these solutions involve major changes to CompareHands. You do not have to fix it using the methods above, we just thought they may be choices you can consider.

Option one : Est ~250
Option two/other choices: Est ~150

**Comment by jalexanderqed** [comment]
F16 OK (200 pts)
