### ISSUE TITLE
Add AI Difficulty Options

### ISSUE THREAD

**Issue by elizamr** [UCSB-CS56-Projects/cs56-games-poker#64]
Currently, there is no option to change the difficulty level on Single Player Mode. This assumes that students have already improved the AI (Issue #55). This would present the player with "Easy," "Intermediate," and "Hard" difficulties. As of now, the AI is fairly weak and easy to beat; this can be a starting point for the "easy" AI. (150 pts)

**Comment by sean-shelton** [comment]
Closing issue because comments have been added to #55
