### ISSUE TITLE
Fix text gathering

### ISSUE THREAD

**Issue by elizamr** [ucsb-cs56-projects/cs56-games-poker#67]
During a match, the informative text and prompts cling to the edges of the frame. Adjust these 
portions slightly so there is a small gap between themselves and the edges. (50 pts)

**Comment by sean-shelton** [comment]
F17 OK (50 pts)

**Comment by Sierrasch** [comment]
W18 OK (50 pts)

**Comment by Sierrasch** [comment]
Solved in W18 by adding a border to the frame
