### ISSUE TITLE
Refactor PokerGameGUI

### ISSUE THREAD

**Issue by elizamr** [ucsb-cs56-projects/cs56-games-poker#71]
Could move creation of all Swing elements in another file. The entire creation of the game is within this file, so similar elements (such as card/deck initialization) can be grouped together. (150 pts)

**Comment by sean-shelton** [comment]
F17 OK (150 pts)

**Comment by Sierrasch** [comment]
W18 OK (150 pts)

**Comment by Sierrasch** [comment]
Completed W18
